version: '3'

services:
  ruby:
    build:
      context: './ruby'
      dockerfile: Dockerfile
    command: bash
    tty: true
    volumes:
      - ./ruby:/ruby
  elixir:
    build:
      context: './elixir'
      dockerfile: Dockerfile
    command: bash
    tty: true
    volumes:
      - ./elixir:/elixir
