version: '3'

services:
  ruby:
    build:
      context: './ruby'
      dockerfile: Dockerfile
    command: bash
    tty: true
    volumes:
      - ./ruby:/ruby
      - ./fixtures:/ruby/fixtures
      - ./docs:/ruby/docs
  elixir:
    build:
      context: './elixir'
      dockerfile: Dockerfile
    command: bash
    tty: true
    volumes:
      - ./elixir:/elixir
      - ./fixtures:/elixir/fixtures
      - /elixir/deps
      - /elixir/_build
